#!/bin/bash
fresh_run=$1
if [[ $fresh_run == 'y' ]]; then
	git clone https://github.com/gnanten/questionaire.git ||true
	repo=$(echo "https://github.com/gnanten/questionaire.git" | cut -d'/' -f5|cut -d'.' -f1)
	cp q3 $repo/
	cd $repo
pwd
fi
current_version=1
tags=$(git tag)
index=0
for version in $tags
do
	version_lst[$index]=${version:$(( ${#version}-1))}
    	index=$((index+1))
done
IFS=$'\n'
max_version=$(echo "${version_lst[*]}" | sort -nru | head -n1)
current_version=$((max_version+1))
d=$(date +%d-%m-%y-%T|cut -d':' -f1)

if [[ current_version ]]; then
	git tag "${d}-Application-v${current_version}"
else
	git tag "${d}-Application-v1"
fi
